spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/demo

mybatis:
  type-aliases-package: com.sram.entity
  mapper-locations: classpath:mapper/*Dao.xml
